### ISSUE TITLE
Geany crash after activate the plugin via Plugins admin in the editor.

### ISSUE THREAD

**Issue by jmarunix** [notetau/geany-jedi-complete#11]
Hi, 
I have Fedora 31, with Geany 1.36.
The plugin makes and installs but in the activation in the editor, the app crash.
These are the messages in the console:

> created jedicomplete
option /usr/bin/python
option /home/jmar/.config/geany/plugins/jedi-complete
option 8080
start jedi server pid:4501
Violación de segmento (`core' generado)

**Comment by constantineav** [comment]
up

**Comment by mixmastamyk** [comment]
Ubuntu 19.10, Geany 1.35

I tried editing the source to upgrade to python3 because that's what I use but a similar thing happened:

```
created jedicomplete
option /usr/bin/python3
option /home/user/.config/geany/plugins/jedi-complete
option 8080
start jedi server pid:25828
fish: “geany” terminated by signal SIGABRT (Abort)
jedi-server: start
```

Also I had to install this to get it to build:

`sudo apt-get install libgtk-3-dev`

**Comment by nickdurante** [comment]
Same problem on Fedora 32, seems like it's trying to bind a port which is used by another process:

```
created jedicomplete
option /usr/bin/python
option /home/nick/.config/geany/plugins/jedi-complete
option 8080
start jedi server pid:20887
free(): double free detected in tcache 2
Traceback (most recent call last):
  File "/home/nick/.config/geany/plugins/jedi-complete/jediserver.py", line 89, in <module>
    server = httpserver.HTTPServer(("localhost", port), Handler)
  File "/usr/lib64/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib64/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
fish: “geany” terminated by signal SIGABRT (Abort)
```

**Comment by KhazAkar** [comment]
I have exactly the same problem as all of you :)
Python 3.8.6rc, Debian Unstable
```
created jedicomplete
option /usr/bin/python
option /home/khazakar/.config/geany/plugins/jedi-complete
option 8080
start jedi server pid:179077
free(): double free detected in tcache 2
Aborted
Traceback (most recent call last):
  File "/home/khazakar/.config/geany/plugins/jedi-complete/jediserver.py", line 89, in <module>
    server = httpserver.HTTPServer(("localhost", port), Handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by ABelliqueux** [comment]
Same with Geany 1.37.1, Python 3.9.1, on Manjaro Linux

The server launches fine with `python ~/.config/geany/plugins/jedi-complete/jediserver.py 8080` , but Geany segfaults right after enabling it.

**Comment by armanaegit** [comment]
up

**Comment by czayas** [comment]
Same error here with Geany 1.38 + Python 3.10.6 running on Manjaro Linux. The Jedi server keeps running but Geany crashes, and when trying to enable the plugin again, it complains that the port is already in use. I have to kill the process manually.

`OSError: [Errno 98] Address already in use`

**Comment by inferrna** [comment]
Edit Makefile, add "-g" to build options, then `gdb /usr/bin/geany`
```gdb
#7  std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~vector() (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/stl_vector.h:683
#8  geanycc::PythonCompletionFramework::updated_preferences() (this=<optimized out>) at src/preferences.cpp:244
#9  0x00007fffdb34a2a6 in geanycc::PythonCompletionFramework::load_preferences() (this=0x55555606a400) at src/preferences.cpp:202
```
With "-O1" instead of "-O2" you can also see `free(): double free detected in tcache 2`

Then build it with "-O0" - wow, no more segfault. Glory to C++ authors :) Then you will see
`TypeError: Script.__init__() takes from 1 to 2 positional arguments but 4 were given`
Fix it with
```diff
diff --git a/src/data/jediserver.py b/src/data/jediserver.py
index e5da194..382b4a0 100644
--- a/src/data/jediserver.py
+++ b/src/data/jediserver.py
@@ -60,8 +60,8 @@ class Handler(httpserver.BaseHTTPRequestHandler):
             # row format: type$typed_text$arguemnt
             return "{0}${1}${2}\n".format(type_, typed_text, arguement)
 
-        script = jedi.Script(source, line, column)
-        completions = script.completions()
+        script = jedi.Script(code=source)
+        completions = script.complete(line=line, column=column)
         # output compltion results
         result = ""
         for c in completions:
```
I hope someone may go further. I surrendered at this stage:
At first use all seems and works correct:
<details>
<summary><b>Good completion</b></summary>
<img src="https://user-images.githubusercontent.com/4245277/196504652-5aec5b08-d874-4361-83f2-4f71eacf0354.jpg">
</details>

But second and others seems like that:
<details>
<summary><b>Completion bad</b></summary>
<img src="https://user-images.githubusercontent.com/4245277/196504649-10927b37-7fc5-4875-9014-b248bdd0057e.jpg">
</details>
